### ISSUE TITLE
add levels to color by sex plot

### ISSUE THREAD

**Issue by khondula** [SESYNC-ci/graphics-with-ggplot2-lesson#5]
around "adding a regression line" section

**Comment by itcarroll** [comment]
Can you remind me more about this issue? We had at one point included a `factor` statement with the levels argument to get "Male" and "Female". Is that what you want back? Maybe put that in the section on labeling plots?

**Comment by khondula** [comment]
This is an issue you asked me to add so I assume it is something you had in mind... I think this is about adding "levels" in the original ggplot aes so it can be used even if its not mapped specifically to a color? http://www.cookbook-r.com/Graphs/Bar_and_line_graphs_(ggplot2)/

**Comment by itcarroll** [comment]
Ah. Thanks.

**Comment by itcarroll** [comment]
Fixed in b0acf72f9bfc03a757e100c0bda3c5f733a00408
